import { topics, topicTrees, exercises, directions } from './model.js';

export function directionPicker(direction) {
  return `<label class="direction-picker">Visual direction <select id="direction">${directions.map((item) => `<option value="${item.id}" ${direction === item.id ? 'selected' : ''}>${item.name} / ${item.description}</option>`).join('')}</select></label>`;
}

export function homeScreen(state, route, ui) {
  const { link, icon, badge } = ui;
  const empty = state.historyDeleted || route.params.get('state') === 'empty';
  const retry = !empty && state.retry?.problem === state.personal.problem ? state.retry : null;
  const exercise = exercises[state.personal.problem];
  const action = empty ? ['Try a guided sample', 'sample'] : retry?.draft ? ['Continue your retry', 'retry'] : state.personal.draft ? ['Continue your interview', 'interview'] : retry?.finished ? ['Explore related practice', 'related'] : ['Open your review', 'review'];
  const stages = [
    { title: 'Attempt saved', description: empty ? 'Start with a sample or your own practice' : exercise.title, done: !empty },
    { title: 'Review the evidence', description: state.reviewOpened && !empty ? 'Review opened · choose what to work on' : 'A stopping condition worth revisiting', done: !empty && state.reviewOpened },
    { title: 'Try it differently', description: retry?.ran ? 'Prepared retry run · guidance used' : 'Fresh practice from a saved checkpoint', done: Boolean(retry?.ran) },
  ];
  return `<div class="home-heading"><div><p class="eyebrow">Your practice / ${empty ? 'A fresh start' : 'In progress'}</p><h1>${empty ? 'Make this your starting point.' : 'Welcome back, Alex.'}</h1><p>${empty ? 'Choose a place to begin. Your journey will build from your attempts.' : 'Pick up the thread. Your last attempt is ready when you are.'}</p></div><div class="profile-caption"><span class="profile-monogram">A</span><span>Demo profile<small>Internship preparation · Python</small></span></div></div>
  <div class="home-layout">
    <section class="focus-work" aria-labelledby="focus-title"><div class="focus-top"><span class="eyebrow">${empty ? 'Begin here' : 'Your next step'}</span>${badge(empty ? 'No activity yet' : retry?.draft || state.personal.draft ? 'Draft saved' : 'Review ready', 'accent')}</div><div class="focus-body"><span class="folio-index" aria-hidden="true">${empty ? '→' : '↳'}</span><p class="small">${empty ? 'Get to know the workspace' : `${exercise.topic} / ${exercise.title}`}</p><h2 id="focus-title">${empty ? 'Try the flow.<br>Find your footing.' : retry?.draft || state.personal.draft ? 'You can start<br>where you left off.' : retry?.finished ? 'Carry the idea<br>into a new problem.' : 'You found the match.<br>What happened next?'}</h2><p>${empty ? 'A prepared attempt lets you explore the interview, evidence, and retry without recording anything.' : 'Revisit the stopping condition in your prepared attempt. Look at the evidence before deciding what to practice.'}</p><div class="actions">${link(action[0], action[1], 'primary', 'arrow')}${link(empty ? 'Start my interview' : 'New interview', 'setup', 'quiet')}</div></div><div class="focus-bottom">${icon('flag')}<span>${empty ? 'The guided sample never counts toward personal activity.' : 'Current focus: stopping at the first qualifying event'}</span></div></section>
    <section class="practice-thread" aria-labelledby="thread-title"><div class="section-heading"><h2 id="thread-title">Your practice thread</h2><span class="small muted">${empty ? 'Not started' : 'Current attempt'}</span></div><ol class="thread-steps">${stages.map((stage, index) => `<li class="${stage.done ? 'recorded' : ''}"><span class="thread-marker" aria-hidden="true">${stage.done ? icon('check') : index + 1}</span><div><h3>${stage.title}</h3><p>${empty ? 'Not started' : stage.description}</p><span class="small ${stage.done ? 'accent-text' : 'muted'}">${stage.done ? 'Recorded in demo' : 'Available when you’re ready'}</span></div></li>`).join('')}</ol><p class="thread-note">Activity, not a readiness score. Guided work stays labeled.</p></section>
    <section class="home-history" aria-labelledby="history-title"><div class="section-heading"><h2 id="history-title">Recent activity</h2>${link('All sessions', 'sessions', 'quiet small', 'arrow')}</div>${empty ? '<p class="empty-inline">Nothing recorded yet. Your attempts and reviews will appear here.</p>' : `<a class="activity-line" href="#${state.personal.draft ? 'interview' : 'review'}"><span class="activity-symbol">${icon('code')}</span><span><strong>${exercise.title}</strong><small>Latest demo attempt · ${state.personal.draft ? 'Draft saved' : 'Review ready'}</small></span>${icon('arrow')}</a><a class="activity-line" href="#interview?problem=alert"><span class="activity-symbol">${icon('clock')}</span><span><strong>First threshold alert</strong><small>Earlier demo activity · Draft saved</small></span>${icon('arrow')}</a><a class="activity-line" href="#review?state=pending&problem=runs"><span class="activity-symbol">${icon('message')}</span><span><strong>First consecutive pair</strong><small>Earlier demo activity · Review pending</small></span>${icon('arrow')}</a>`}</section>
    <section class="home-route" aria-labelledby="route-title"><div class="section-heading"><h2 id="route-title">Your learning path</h2>${link('Open roadmap', 'roadmap', 'quiet small', 'map')}</div><div class="path-preview"><span>Sequences</span><span aria-hidden="true">→</span><a href="#roadmap?topic=sets">Maps & sets ${icon('expand')}</a><span aria-hidden="true">→</span><span>Repeated values</span></div><p>Explore a topic, open its subtopics, then choose a problem.</p></section>
  </div><div class="home-bottom"><span>Fictional profile and activity · nothing here measures mastery</span>${link(state.sampleRoute !== 'sample' ? 'Resume the guided sample' : 'Explore the guided sample', state.sampleRoute, 'quiet small')}${link('Example review', 'review?source=sample', 'quiet small')}</div>`;
}

export function roadmapScreen(state, route, ui) {
  const { link, button, icon } = ui;
  const view = route.params.get('view') ?? (matchMedia('(max-width: 48rem)').matches ? 'list' : 'map');
  const selected = topics.find((topic) => topic.id === route.params.get('topic'));
  const node = (topic) => `<a id="topic-${topic.id}" href="#roadmap?topic=${topic.id}&view=${view}" class="topic-node" style="--column:${topic.column};--row:${topic.row}" aria-label="Open ${topic.name}"><span class="node-inner"><span class="node-heading">${topic.name}${icon('expand')}</span><span class="node-description">${topic.note}</span><span class="node-status">${topicTrees[topic.id].length} subtopics · Explore</span></span></a>`;
  return `<div class="page-title"><div><p class="eyebrow">Your learning path</p><h1>Learning roadmap</h1><p>Open a topic. Follow the idea. Find your next problem.</p></div>${link('Start an interview', 'setup', 'secondary', 'play')}</div><div class="roadmap-toolbar"><div class="actions"><div class="segmented" aria-label="Roadmap view">${link('Map', `roadmap?view=map${selected ? `&topic=${selected.id}` : ''}`, view === 'map' ? 'selected' : '', 'map')}${link('List', `roadmap?view=list${selected ? `&topic=${selected.id}` : ''}`, view === 'list' ? 'selected' : '', 'list')}</div><span class="small muted">Python · original practice</span></div>${button('How to use the map', 'map-help', 'quiet', 'book')}</div>
  ${selected ? `<nav class="topic-context" aria-label="Roadmap topics">${topics.map((topic) => `<a href="#roadmap?topic=${topic.id}&view=${view}" ${selected.id === topic.id ? 'aria-current="page"' : ''}>${topic.name}</a>`).join('')}</nav><section class="topic-expanded" aria-labelledby="topic-title"><div class="expanded-heading"><div><p class="eyebrow">Roadmap / topic opened</p><h2 id="topic-title" tabindex="-1">${selected.name}</h2><p>${selected.note}. Choose a practice node to see its problems.</p></div><a class="icon-button" aria-label="Close topic detail" href="#roadmap?view=${view}&return=${selected.id}">${icon('close')}</a></div><div class="subtopic-map ${view === 'list' ? 'linear-tree' : ''}"><div class="tree-origin"><span class="small muted">Topic</span><strong>${selected.name}</strong>${icon('map')}</div><ul class="branch-tree" aria-label="Subtopics in ${selected.name}">${topicTrees[selected.id].map((branch) => `<li><div class="branch-label"><span class="small muted">Subtopic</span><h3>${branch.name}</h3><p>${branch.note}</p></div><ul>${branch.leaves.map((leaf) => `<li><a class="practice-leaf" id="leaf-${leaf.id}" href="#roadmap?topic=${selected.id}&view=${view}&leaf=${leaf.id}" aria-haspopup="dialog"><span class="small muted">Practice</span><strong>${leaf.name}</strong><span class="leaf-foot">${leaf.exercises.length} ${leaf.exercises.length === 1 ? 'problem' : 'problems'} ${icon('arrow')}</span></a></li>`).join('')}</ul></li>`).join('')}</ul></div><div class="map-legend"><span class="legend-line" aria-hidden="true"></span>Topic → subtopic → practice → problem list<span class="muted">A suggested path, not a requirement</span></div></section>` : `<section class="map-panel" aria-label="Practice topics"><div class="map-section-label"><span>Foundations</span><span>Patterns in practice</span><span>Apply the idea</span></div>${view === 'map' ? `<div class="map-scroll" tabindex="0" role="region" aria-label="Learning map, scroll horizontally for more topics"><div class="map-grid"><svg class="connectors" viewBox="0 0 1000 460" preserveAspectRatio="none" aria-hidden="true"><path d="M240 225C295 225 275 78 340 78M240 225C295 225 275 370 340 370M565 78H670M565 370H670"/></svg>${topics.map(node).join('')}</div></div>` : `<div class="topic-list">${topics.map(node).join('')}</div>`}<div class="map-legend"><span class="legend-line" aria-hidden="true"></span>Connections suggest an order. Every topic is open.<span class="actions">${view === 'map' ? `${button('Pan left', 'pan-left', 'quiet small', 'back')}${button('Pan right', 'pan-right', 'quiet small', 'arrow')}` : ''}</span></div></section>`}<p class="catalog-note">Illustrative catalog · exercises can appear under more than one skill. No locked topics or mastery scores.</p>`;
}

export function getPracticeLeaf(route) {
  const topic = topics.find((item) => item.id === route.params.get('topic'));
  const leaf = topicTrees[topic?.id]?.flatMap((branch) => branch.leaves).find((item) => item.id === route.params.get('leaf'));
  return leaf ? { topic, leaf } : null;
}

export function problemDrawer(selection, ui) {
  const { button, link, icon } = ui;
  return `<div class="drawer-heading"><span class="eyebrow">${selection.topic.name} / practice</span>${button('Close problems', 'close-problems', 'quiet small', 'close')}</div><h2 id="drawer-title">${selection.leaf.name}</h2><p>Choose a problem to set up your interview.</p><div class="drawer-meta"><span>${selection.leaf.exercises.length} available</span><span>Original · Python</span></div><ol class="drawer-problems">${selection.leaf.exercises.map((id, index) => `<li><span class="problem-number">${String(index + 1).padStart(2, '0')}</span><div><h3>${exercises[id].title}</h3><p>${exercises[id].lead}</p>${link('Set up interview', `setup?problem=${id}`, 'secondary', 'arrow')}</div></li>`).join('')}</ol><div class="drawer-note">${icon('book')}<p>Choosing a problem opens setup. Nothing starts or records automatically.</p></div>`;
}
