// Regenerates migrations/0005_problem_bank.sql from pinned public datasets.
// Reference solutions run only inside a disposable, network-less container.
// See docs/problem-bank.md for sources, licenses, and selection rules.
import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
const docker = process.env.PYTHON_RUNNER_DOCKER ?? "docker";
const image = process.env.PROBLEM_BANK_IMAGE ?? "python:3.12-slim-bookworm";
const sources = [
  { file: "sanitized-mbpp.json", url: "https://raw.githubusercontent.com/google-research/google-research/master/mbpp/sanitized-mbpp.json", sha256: "ca95deaa9a01ef0a6f439f88bcf0dd3db3563d22f22aad6cae04ebb9a8d8c8e9" },
  { file: "HumanEval.jsonl.gz", url: "https://raw.githubusercontent.com/openai/human-eval/master/data/HumanEval.jsonl.gz", sha256: "b796127e635a67f93fb35c04f4cb03cf06f38c8072ee7cee8833d7bee06979ef" },
];

function run(command, args) {
  return new Promise((resolveRun, reject) => {
    const child = spawn(command, args, { stdio: ["ignore", "inherit", "inherit"] });
    child.on("error", reject);
    child.on("exit", (code) => (code === 0 ? resolveRun() : reject(new Error(`${command} exited ${code}`))));
  });
}

// PostgreSQL standard_conforming_strings: only single quotes need escaping.
const literal = (value) => `'${String(value).replaceAll("'", "''")}'`;
const jsonb = (value) => `${literal(JSON.stringify(value))}::jsonb`;

const directory = await mkdtemp(join(tmpdir(), "problem-bank-"));
try {
  for (const source of sources) {
    const response = await fetch(source.url);
    if (!response.ok) throw new Error(`Download failed (${response.status}): ${source.url}`);
    const bytes = Buffer.from(await response.arrayBuffer());
    const digest = createHash("sha256").update(bytes).digest("hex");
    if (digest !== source.sha256) throw new Error(`${source.file} changed upstream (sha256 ${digest}). Review it, then update the pin.`);
    await writeFile(join(directory, source.file), bytes);
  }
  await writeFile(join(directory, "build.py"), await readFile(resolve(import.meta.dirname, "build.py")));
  await run(docker, ["run", "--rm", "--network=none", "--memory=1g", "--pids-limit=256", "--cap-drop=ALL", "--security-opt=no-new-privileges", "-v", `${directory}:/work`, image, "python3", "-I", "/work/build.py", "/work", "/work/problems.json"]);
  const { problems } = JSON.parse(await readFile(join(directory, "problems.json"), "utf8"));
  const lines = [
    "-- Generated by scripts/problem-bank/build.mjs. Do not edit by hand.",
    "-- Sources: MBPP-sanitized (CC BY 4.0, Google) and HumanEval (MIT, OpenAI).",
    "-- Attribution, licenses, and selection rules: docs/problem-bank.md.",
    "",
  ];
  for (const problem of problems) {
    lines.push(`INSERT INTO problems (id, problem_family_id, revision, title, topic, difficulty, prompt, starter_code, reference_solution, clarification_guidance, help_guidance, entry_point, test_contract, is_sample) VALUES (${[problem.id, problem.familyId].map(literal).join(", ")}, 1, ${[problem.title, problem.topic, problem.difficulty, problem.prompt, problem.starterCode, problem.referenceSolution, problem.clarificationGuidance, problem.helpGuidance, problem.entryPoint].map(literal).join(", ")}, ${jsonb(problem.testContract)}, false);`);
    for (const test of problem.tests) {
      lines.push(`INSERT INTO test_cases (id, problem_id, input_data, expected_output, visibility) VALUES (${literal(test.id)}, ${literal(problem.id)}, ${jsonb(test.inputData)}, ${jsonb(test.expectedOutput)}, ${literal(test.visibility)});`);
    }
  }
  await writeFile(resolve(root, "migrations/0005_problem_bank.sql"), `${lines.join("\n")}\n`);
  const count = (key) => Object.entries(Object.groupBy(problems, (problem) => problem[key])).map(([name, items]) => `${name}: ${items.length}`).join(", ");
  console.log(`Wrote ${problems.length} verified problems.\nTopics — ${count("topic")}\nDifficulty — ${count("difficulty")}`);
} finally {
  await rm(directory, { recursive: true, force: true });
}
